{
  "MD013": false, # Line length limitation
  "MD024": false, # Allow multiple headings with the same content
  "MD033": false, # Enable Inline HTML
  "MD041": false, # Allow first line heading
  "MD045": false, # Allow Images have no alternate text
}