#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: Release

on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:
    inputs:
      live-run:
        type: boolean
        description: If false (or undefined) the workflow runs in dry-run mode (i.e. with no side-effects)
        required: false
      version:
        type: string
        description: Release number. If undefined, the workflow auto-generates a version using git-describe
        required: false
      zenoh-version:
        type: string
        description: Release number of Zenoh. Required in live-run mode and ignored in dry-run mode
        required: false

jobs:
  tag:
    name: Bump and tag crates
    uses: eclipse-zenoh/ci/.github/workflows/tag-crates.yml@main
    with:
      repo: ${{ github.repository }}
      live-run: ${{ inputs.live-run }}
      version: ${{ inputs.version }}
      inter-deps-pattern: ${{ inputs.live-run && 'zenoh.*' || '^$' }}
      inter-deps-version: ${{ inputs.live-run && inputs.zenoh-version || '' }}
    secrets: inherit

  build-debian:
    name: Build Debian packages
    needs: tag
    uses: eclipse-zenoh/ci/.github/workflows/build-crates-debian.yml@main
    with:
      repo: ${{ github.repository }}
      version: ${{ needs.tag.outputs.version }}
      branch: ${{ needs.tag.outputs.branch }}
    secrets: inherit

  build-standalone:
    name: Build executables and libraries
    needs: tag
    uses: eclipse-zenoh/ci/.github/workflows/build-crates-standalone.yml@main
    with:
      repo: ${{ github.repository }}
      version: ${{ needs.tag.outputs.version }}
      branch: ${{ needs.tag.outputs.branch }}
      artifact-patterns: |
        ^libzenoh_backend_influxdb(2)\.(dylib|so)$
        ^zenoh_backend_influxdb(2)\.dll$
    secrets: inherit

  cargo-live-run:
    if: ${{ inputs.live-run }}
    name: Publish Cargo crates (live-run)
    needs: tag
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-cargo.yml@main
    with:
      repos: ${{ github.repository }}
      live-run: true
      branch: ${{ needs.tag.outputs.branch }}
      inter-deps-pattern: ^$
    secrets: inherit

  # In dry-run mode, we need to publish eclipse-zenoh/zenoh before this repository,
  # in which case the version of zenoh dependecies are left as is and thus point to
  # the main branch of eclipse-zenoh/zenoh
  cargo-dry-run:
    if: ${{ !inputs.live-run }}
    name: Publish Cargo crates (dry-run)
    needs: tag
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-cargo.yml@main
    with:
      repos: |
        eclipse-zenoh/zenoh
        ${{ github.repository }}
      live-run: false
      branch: ${{ needs.tag.outputs.branch }}
      inter-deps-pattern: zenoh.*
    secrets: inherit

  debian:
    name: Publish Debian packages
    needs: [tag, build-debian]
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-debian.yml@main
    with:
      no-build: true
      live-run: ${{ inputs.live-run }}
      version: ${{ needs.tag.outputs.version }}
      repo: ${{ github.repository }}
      branch: ${{ needs.tag.outputs.branch }}
    secrets: inherit

  homebrew:
    name: Publish Homebrew formulae
    needs: [tag, build-standalone]
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-homebrew.yml@main
    with:
      no-build: true
      repo: ${{ github.repository }}
      live-run: ${{ inputs.live-run }}
      version: ${{ needs.tag.outputs.version }}
      branch: ${{ needs.tag.outputs.branch }}
      artifact-patterns: |
        ^libzenoh_backend_influxdb(2)\.dylib$
      formulae: |
        zenoh-backend-influxdb
    secrets: inherit

  eclipse:
    name: Publish artifacts to Eclipse downloads
    needs: [tag, build-standalone]
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-eclipse.yml@main
    with:
      no-build: true
      live-run: ${{ inputs.live-run }}
      version: ${{ needs.tag.outputs.version }}
      repo: ${{ github.repository }}
      branch: ${{ needs.tag.outputs.branch }}
      artifact-patterns: |
        ^libzenoh_backend_influxdb(2)\.(dylib|so)$
        ^zenoh_backend_influxdb(2)\.dll$
      name: zenoh-backend-influxdb
    secrets: inherit

  github:
    name: Publish artifacts to GitHub Releases
    needs: [tag, build-standalone]
    uses: eclipse-zenoh/ci/.github/workflows/release-crates-github.yml@main
    with:
      no-build: true
      live-run: ${{ inputs.live-run }}
      version: ${{ needs.tag.outputs.version }}
      repo: ${{ github.repository }}
      branch: ${{ needs.tag.outputs.branch }}
      artifact-patterns: |
        ^libzenoh_backend_influxdb(2)\.(dylib|so)$
        ^zenoh_backend_influxdb(2)\.dll$
    secrets: inherit
